### ISSUE TITLE
Release sql-logic-test version 0.1

### ISSUE THREAD

**Issue by julianhyde** [hydromatic/sql-logic-test#15]
Release SQL-Logic-Test version 0.1.

This will be the first release of SQL-Logic-Test. Goals:
 * Someone could download from GitHub, build and run tests against HSQLDB or Postgres
 * Deploy artifacts to Maven central
 * Enable https://issues.apache.org/jira/browse/CALCITE-5615 to be implemented based on those Maven central artifacts
 * Good enough release notes, web site for people to discover the component
 * Correct licensing, and consent of all copyright holders

@mbudiu-vmw and @zabetak, Are there any goals I missed? Are there any critical bugs that need to be fixed in order to meet these goals? If we're good I will create a release candidate.

**Comment by mbudiu-vmw** [comment]
I have fixed a few bugs in the code that was originally submitted, I would like to port these fixes to the new version of the software once it's ready before we do a release. Should I file issues for these bugs?

**Comment by julianhyde** [comment]
We should follow the open source mantra, 'release early and often'.

Let's assume there will be a release 0.2 in a month or two. When you log bugs, figure out whether they are critical for 0.1 or can wait until 0.2.

**Comment by mbudiu-vmw** [comment]
Let me fix these today.

**Comment by mbudiu-vmw** [comment]
I sent #20 to fix #17.
However, it would be nice to also fix #19 before the 0.1 release.
I think #18 can wait for 0.2.

**Comment by mbudiu-vmw** [comment]
And also I am eager to run the tests on various incarnations of Calcite.

**Comment by julianhyde** [comment]
Me too!

OK, I'll release 0.1 over the weekend. If there are bugs then 0.2 will follow soon afterwards.

**Comment by mbudiu-vmw** [comment]
I will see whether I can fix #18 today.

**Comment by zabetak** [comment]
The plan sounds good to me; sorry for not replying earlier but I was travelling.

We may want to try to rework CALCITE-5615 before cutting the release to ensure that we haven't missed something important for consumers but as you feel.

**Comment by julianhyde** [comment]
Fixed in d85f7edf290c757feafe9e06cbbdd0868445d9d6.

@zabetak, If we've missed something necessary to support CALCITE-5615 (and we probably have) then let's make release 0.2 soon.
