### ISSUE TITLE
JdbcExecutor is not extensible

### ISSUE THREAD

**Issue by zabetak** [hydromatic/sql-logic-test#24]
The `JdbcExecutor` class seems to be a class designed for extension but it contains `abstract` methods that are package private making it very difficult to create sub-classes of it. 

I thought that I could build a `CalciteExecutor` by extending `JdbcExecutor` but it is not possible to do so unless I put the extensions in the `net.hydromatic` namespace and under exactly the same package that is not ideal.

**Comment by zabetak** [comment]
@mbudiu-vmw is it appropriate to create extensions of `JdbcExecutor` or not? If yes then I guess we should revisit the visibility of certain methods.

**Comment by mbudiu-vmw** [comment]
This is an oversight. Should have written a test for this.

**Comment by mbudiu-vmw** [comment]
I will submit a PR with the required changes once I figure out what else needs to be visible.
We probably will need to make a new release.

**Comment by mihaibudiu** [comment]
Fixed by #25
